// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_nice_score = "CgkIlN-D98YDEAIQCA"; // <GPGSID>
        public const string achievement_amazing_score__are_you_high_on_the_leaderboard = "CgkIlN-D98YDEAIQCQ"; // <GPGSID>
        public const string achievement_so_you_think_you_can_take_on_infinite_mode = "CgkIlN-D98YDEAIQBw"; // <GPGSID>
        public const string achievement_incredible_score__check_the_leaderboard = "CgkIlN-D98YDEAIQCg"; // <GPGSID>
        public const string achievement_baby_steps = "CgkIlN-D98YDEAIQAg"; // <GPGSID>
        public const string achievement_your_full_potential_has_almost_been_reached = "CgkIlN-D98YDEAIQBg"; // <GPGSID>
        public const string leaderboard_levels_completed = "CgkIlN-D98YDEAIQAw"; // <GPGSID>
        public const string achievement_your_power_is_becoming_immense = "CgkIlN-D98YDEAIQBQ"; // <GPGSID>
        public const string leaderboard_infinite_mode_high_score = "CgkIlN-D98YDEAIQAQ"; // <GPGSID>
        public const string achievement_the_art_of_portal_placing = "CgkIlN-D98YDEAIQBA"; // <GPGSID>

}

